language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=x86
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-27
  - extra-android-m2repository
  - $ANDROID_TARGET
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew assembleDebug
  - ./gradlew assembleAndroidTest
  - ./gradlew lintDebug
